status = warn
name = PeopleCounterLocal

appender.console.type = Console
appender.console.name = stderr
appender.console.target = SYSTEM_ERR
appender.console.layout.type = JsonTemplateLayout
appender.console.layout.eventTemplateUri = classpath:EcsLayout.json

rootLogger.level = info
rootLogger.appenderRef.stderr.ref = stderr

logger.jetty.name = org.sparkproject.jetty
logger.jetty.level = warn
